<?php /* @var $this Creativestyle_TransactionalEmailCopy_Block_Adminhtml_System_Config_Field_Infoblock */ ?>
<tr>
    <td colspan="4">
        <img width="78" src="<?php echo $this->getSkinUrl('images/creativestyle_transactionalemailcopy/logo.svg') ?>" style="float: left;"/>
        <table style="float: left;margin-left:20px;margin-bottom: 10px;">
            <tr>
                <td width="110"><b><?php echo $this->__('Name');?>:</b></td>
                <td><b>Creativestyle TransactionalEmailCopy (version <?php echo Mage::getConfig()->getNode()->modules->Creativestyle_TransactionalEmailCopy->version;?>)</b></td>
            </tr>
            <tr>
                <td><b><?php echo $this->__('Description');?>:</b></td>
                <td><?php echo $this->__('This extension adds massaction column and allows you to mass delete templates and copy with desired prefix and suffix.');?></td>
            </tr>
            <tr>
                <td><b><?php echo $this->__('Contact');?>:</b></td>
                <td>Adam Karnowka (<a href="mailto:adam.karnowka@creativestyle.pl">adam.karnowka@creativestyle.pl</a>)</td>
            </tr>
            <tr>
                <td><b><?php echo $this->__('More info');?>:</b></td>
                <td>
                    <a href="https://github.com/adamkarnowka/magento-transactional-email-copy"><?php echo $this->__('Extension documentation');?></a>
                </td>
            </tr>
        </table>
    </td>
</tr>